// <auto-generated />
using System;
using Campanhas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Campanhas.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611130729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identidade")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Campanhas.Domain.Entities.Campanhas.Campanha", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("StatusCampanha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status_campanha");

                    b.Property<decimal>("ValorArrecadado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_arrecadado");

                    b.HasKey("Guid");

                    b.ToTable("campanha", "operacao");
                });

            modelBuilder.Entity("Campanhas.Domain.Entities.Campanhas.Campanha", b =>
                {
                    b.OwnsOne("Campanhas.Domain.Entities.Campanhas.MetaFinanceira", "MetaFinanceira", b1 =>
                        {
                            b1.Property<Guid>("CampanhaGuid")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("meta_financeira");

                            b1.HasKey("CampanhaGuid");

                            b1.ToTable("campanha", "operacao");

                            b1.WithOwner()
                                .HasForeignKey("CampanhaGuid");
                        });

                    b.OwnsOne("Campanhas.Domain.Entities.Campanhas.TituloCampanha", "Titulo", b1 =>
                        {
                            b1.Property<Guid>("CampanhaGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("titulo");

                            b1.HasKey("CampanhaGuid");

                            b1.ToTable("campanha", "operacao");

                            b1.WithOwner()
                                .HasForeignKey("CampanhaGuid");
                        });

                    b.Navigation("MetaFinanceira")
                        .IsRequired();

                    b.Navigation("Titulo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
