// <auto-generated />
using System;
using Campanhas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Campanhas.Infrastructure.Migrations
{
    [DbContext(typeof(CampanhaDbContext))]
    partial class CampanhaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Campanhas.Domain.Entities.Campanha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataModificacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StatusCampanha")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorArrecadado")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Campanhas", (string)null);
                });

            modelBuilder.Entity("Campanhas.Domain.Entities.Campanha", b =>
                {
                    b.OwnsOne("Campanhas.Domain.ValueObjects.MetaFinanceira", "MetaFinanceira", b1 =>
                        {
                            b1.Property<Guid>("CampanhaId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("MetaFinanceira");

                            b1.HasKey("CampanhaId");

                            b1.ToTable("Campanhas");

                            b1.WithOwner()
                                .HasForeignKey("CampanhaId");
                        });

                    b.OwnsOne("Campanhas.Domain.ValueObjects.TituloCampanha", "Titulo", b1 =>
                        {
                            b1.Property<Guid>("CampanhaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Titulo");

                            b1.HasKey("CampanhaId");

                            b1.ToTable("Campanhas");

                            b1.WithOwner()
                                .HasForeignKey("CampanhaId");
                        });

                    b.Navigation("MetaFinanceira")
                        .IsRequired();

                    b.Navigation("Titulo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
